# HotFurnaceItems By WINGS7
# Chance in percents, sound time in ticks
# Materials - https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# Effects - https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
